[tasks.test_correct_hands]
command = "cargo"
args = [
    "test",
    "correct_hands",
    "--release",
    "--features",
    "test",
    "--",
    "--ignored",
]

[tasks.test_verify_correctness]
command = "cargo"
args = [
    "test",
    "verify_correctness",
    "--release",
    "--features",
    "correctness",
    "--",
    "--ignored",
]
